# General settings
wallpaper=./wallpapers/0001.jpg

# Swaybg-like fill modes
fill_mode=stretch   # Options: stretch, fit, fill, center, tile

background_color= #000000  # Background color if the wallpaper doesn't fill the screen
